name: Build&Release LaTeX Document

on:
  push:
    tags:
      - "task*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v2
      - name: Compile and execute
        run: make run
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          latexmk_shell_escape: true
      - name: Zip output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r data.zip data
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            report.pdf
            data.zip

permissions:
  contents: write